version: "3.7"

services:

    postgres:
      container_name: 'messaging-app-database'
      image: 'postgres:11.2'
      restart: always
      ports:
        - '5432:5432'
      environment:
        - 'POSTGRES_USER=user'
        - 'POSTGRES_DB=admin'
        - 'POSTGRES_PASSWORD=password'

#    redis:
#      container_name: 'virtual-ed-redis-dev'
#      image: 'redis:5.0.5'
#      ports:
#        - '6379:6379'
